# Generated by Django 5.2.17 on 2026-09-16 09:57

import django.db.models.deletion
from django.db import migrations, models

import kernel_tracker.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "head",
                    kernel_tracker.fields.OidField(verbose_name="series head OID"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("p", "patchset"), ("m", "merge request")],
                        max_length=1,
                        verbose_name="series kind",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="series name"
                    ),
                ),
                ("link", models.URLField(blank=True, verbose_name="series link")),
            ],
            options={
                "verbose_name_plural": "series",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Tree",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(unique=True, verbose_name="tree name")),
                ("url", models.CharField(max_length=200, verbose_name="tree URL")),
                (
                    "branch",
                    models.CharField(
                        default="main", max_length=64, verbose_name="remote branch"
                    ),
                ),
                (
                    "head",
                    kernel_tracker.fields.OidField(
                        blank=True, verbose_name="last processed commit"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("u", "upstream"), ("d", "downstream")],
                        max_length=1,
                        verbose_name="tree kind",
                    ),
                ),
                (
                    "is_vanilla",
                    models.BooleanField(
                        default=False, verbose_name="is this Linus's tree?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "git tree",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oid",
                    kernel_tracker.fields.OidField(
                        unique=True, verbose_name="commit OID"
                    ),
                ),
                ("is_merge", models.BooleanField(default=False)),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="position in series"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "upstream",
                    models.ManyToManyField(
                        blank=True,
                        related_name="downstream",
                        to="kernel_tracker.commit",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commits",
                        to="kernel_tracker.series",
                    ),
                ),
                (
                    "trees",
                    models.ManyToManyField(
                        blank=True, related_name="commits", to="kernel_tracker.tree"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        max_length=512, unique=True, verbose_name="file path"
                    ),
                ),
                (
                    "commits",
                    models.ManyToManyField(
                        blank=True, related_name="files", to="kernel_tracker.commit"
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="MissingFix",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_reported", models.BooleanField(default=False)),
                (
                    "fixed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="kernel_tracker.commit",
                    ),
                ),
                (
                    "fixing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missing_upstream_fixes",
                        to="kernel_tracker.commit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VanillaVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="version"
                    ),
                ),
                (
                    "commit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tags",
                        to="kernel_tracker.commit",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="tree",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="origins",
                to="kernel_tracker.vanillaversion",
                verbose_name="forked from",
            ),
        ),
        migrations.AddField(
            model_name="commit",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commits",
                to="kernel_tracker.vanillaversion",
            ),
        ),
        migrations.CreateModel(
            name="Fix",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "mention"),
                            ("f", "explicit fix"),
                            ("r", "revert"),
                        ],
                        max_length=1,
                        verbose_name="fix type",
                    ),
                ),
                (
                    "fixed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixing_info",
                        to="kernel_tracker.commit",
                    ),
                ),
                (
                    "fixing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_by_info",
                        to="kernel_tracker.commit",
                    ),
                ),
            ],
            options={
                "unique_together": {("fixing", "fixed_by")},
            },
        ),
        migrations.CreateModel(
            name="SeriesCommit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="position in series"
                    ),
                ),
                (
                    "commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commit_series",
                        to="kernel_tracker.commit",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series_commits",
                        to="kernel_tracker.series",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("series", "commit")},
            },
        ),
        migrations.CreateModel(
            name="TreeAlias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200, verbose_name="alias URL")),
                (
                    "branch",
                    models.CharField(
                        default="main", max_length=64, verbose_name="alias branch"
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="kernel_tracker.tree",
                    ),
                ),
            ],
            options={
                "unique_together": {("tree", "url", "branch")},
            },
        ),
    ]
