# Generated by Django 5.2.17 on 2026-09-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernel_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tree",
            name="is_vanilla",
            field=models.BooleanField(
                default=False, verbose_name="is this the vanilla tree?"
            ),
        ),
    ]
