# Generated by Django 5.2.17 on 2026-10-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernel_tracker", "0002_alter_tree_is_vanilla"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False, verbose_name="enable scheduled updates"
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        default="0 * * * *",
                        help_text="every hour by default, in the configured timezone",
                        max_length=100,
                        verbose_name="cron expression",
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last update"
                    ),
                ),
            ],
            options={
                "verbose_name": "update schedule",
            },
        ),
    ]
